In [1]:
import numpy as np

In [2]:
p = np.array([[1.0, 2.0, 10],
 [3.0, 4.0, 20],
 [5.0, 6.0, 30],
 [7.0, 8.0, 40]])

In [3]:
p

array([[ 1.,  2., 10.],
       [ 3.,  4., 20.],
       [ 5.,  6., 30.],
       [ 7.,  8., 40.]])

In [27]:
z = p[:,2].reshape(4,1)
z

array([[10.],
       [20.],
       [30.],
       [40.]])

In [28]:
p/z

array([[0.1       , 0.2       , 1.        ],
       [0.15      , 0.2       , 1.        ],
       [0.16666667, 0.2       , 1.        ],
       [0.175     , 0.2       , 1.        ]])