In [1]:
import numpy as np

a. Create a null vector of size 10 but the fifth value which is 1

In [7]:
null_vector = np.zeros(10)

In [9]:
null_vector[[5]] = 1

In [10]:
null_vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

b. Create a vector with values ranging from 10 to 49

In [48]:
range_vector = np.arange(10,50)

In [26]:
range_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

c. Reverse a vector (first element becomes last)

In [27]:
range_vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

d. Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
matrix_array = np.arange(9).reshape(3,3)

In [29]:
matrix_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [37]:
indices_array = np.array([1,2,0,0,4,0])

In [42]:
filtered_array = indices_array > 0
filtered_array

array([ True,  True, False, False,  True, False])

In [43]:
indices_array[filtered_array]

array([1, 2, 4])

f. Create a random vector of size 30 and find the mean value

In [45]:
random_vector = np.random.rand(30)
random_vector

array([0.77946161, 0.63818433, 0.17829607, 0.68609611, 0.48738454,
       0.76384405, 0.31766755, 0.53906372, 0.91832335, 0.25061843,
       0.80992334, 0.02471659, 0.18875139, 0.052678  , 0.47510581,
       0.98779319, 0.17782689, 0.5588455 , 0.12395451, 0.68877035,
       0.62158374, 0.39274756, 0.81177326, 0.7653139 , 0.37852418,
       0.17748969, 0.1314127 , 0.4351726 , 0.25247114, 0.04685231])

In [46]:
random_vector.mean()

np.float64(0.45535488020111703)

g. Create a 2d array with 1 on the border and 0 inside

In [66]:
shape = 3
d_array = np.zeros(9).reshape(shape,shape)
d_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
d_array[0, :] = 1
d_array[-1, :] = 1
d_array[:, -1] =1
d_array[:, 0] = 1

In [76]:
d_array

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [102]:
c_array = np.zeros(64).reshape(8,8)
c_array 

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [105]:
c_array[1::2, ::2] = 1
c_array[::2, 1::2] = 1

In [106]:
c_array

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

i. Create a checkerboard 8x8 matrix using the tile function

In [118]:
t_array1 = np.array([[0., 1.], 
                    [1., 0.]])

In [120]:
np.tile(t_array1, (4,4))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

j. Given a 1D array, negate all elements which are between 3 and 8, in place

In [127]:
Z = np.arange(11)
B = np.where((Z>2) & (Z<8))
Z[B] *= -1
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9, 10])

k. Create a random vector of size 10 and sort it

In [129]:
Z = np.random.random(10)
np.sort(Z)

array([0.01658234, 0.03388193, 0.08853413, 0.34863128, 0.45289658,
       0.62473099, 0.62585167, 0.68657129, 0.75230824, 0.89254372])

l. Consider two random array A anb B, check if they are equal

In [131]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

m. How to calculate the square of every number in an array in place (without creating temporaries)?

In [133]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z

int32


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [134]:
Z *=Z

In [135]:
Z

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

n. How to get the diagonal of a dot product?

In [137]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
C

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [138]:
D = np.diagonal(C)

In [139]:
D

array([ 18,  66, 132])